site_name: OpenDNSSEC
docs_dir: website

plugins:
  - include-markdown
  - mermaid2
  - search
  - exclude-search:
      exclude:
        - '*.txt'
        - 'howto.md'
      exclude_unreferenced: false
  - section-index

extra_css:
  - stylesheets/extra.css

theme:
  name: material
  logo: assets/logo.png
  extra: https://www.opendnssec.org/
  palette:
    primary: custom
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.sections
  hide:
    - navigation

markdown_extensions:
  - pymdownx.details:

extra_javascript:
  - https://unpkg.com/mermaid@10.6.1/dist/mermaid.min.js

nav:
  - 'Home':
    - 'index.md'
  - 'Migration from 1.4 to 2.1':
    - 'migration.md'
  - 'About':
    - 'about.md'